modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="advanced_inventory"
version="${file.jarVersion}"
displayName="Advanced Inventory"
authors="Zanckor, Arcane Studios"

description='''

'''

[[dependencies.advanced_inventory]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.advanced_inventory]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.21)"
   ordering="NONE"
   side="BOTH"
